version: '3.1'

services:

  db:
    image: mariadb
    container_name: vedita-database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

//инициализация базы данных с помощью команды sudo docker-compose up