version: '3'
services:
 nginx:
  image: nginx:latest
  ports: ["80:80"]
  volumes: 
  - ".src:/var/www/html"
  - ".docker/nginx/conf.d:/etc/nginx/conf.d"

 php:
  image: php:7.4-fpm
  volumes: [".src:/var/www/html"]